baseurl: ''
permalink: pretty
title: Look and Paws
slogan: For people with sass pets and bouji floofs

# --------------------------------------------- #
#   Configure Social Media Links On Home Page   #
# --------------------------------------------- #

socialMediaButtons:
  - socialMediaCompanyName: instagram
    url: https://instagram.com/lookandpawsofficial
  - socialMediaCompanyName: facebook
    url: https://www.facebook.com/lookandpaws/

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
