baseurl: ''
permalink: pretty
title: Look and Paws
slogan: Sassy petwear for bouji floofs

logoLong: /images/Look_and_Paws_Logo_Long.png

instagramUrl: https://instagram.com/lookandpawsofficial
twitterUrl: https://twitter.com/lookandpaws
linktreeUrl: https://linktr.ee/lookandpaws

blogHomePageUrl: /blog

blogTitleOne: How To Keep Your Pet Entertained During Lockdown
blogDescriptionOne: Description text goes here
blogPostedDateOne: March 21st, 2020
blogAuthoredByOne: Look and Paws
blogLandscapeImageOne: /images/Look_and_Paws_Blog_How_To_Keep_Your_Pet_Entertained_During_Lockdown_1.jpg
blogUrlOne: /blog/how-to-keep-pet-entertained-during-lockdown
blogMetaKeywordTagsOne:

blogTitleTwo: Keeping Your Pet Calm During Lockdown
blogDescriptionTwo: Pets, in particular dogs, do not always deal very well with a sudden change in routine. Fortunately, we’ve put together a series of steps you can follow, to ensure that things go as smoothly as possible for you and your furry friend during lockdown!
blogPostedDateTwo: March 26th, 2020
blogAuthoredByTwo: Look and Paws
blogLandscapeImageTwo: /images/Look_and_Paws_Blog_Keeping_Your_Pet_Calm_During_Lockdown_1.jpg
blogUrlTwo: /blog/keeping-your-pet-calm-during-lockdown
blogMetaKeywordTagsTwo:

plugins:
  - jekyll-environment-variables
