baseurl: ''
permalink: pretty
title: Look and Paws
slogan: Sassy petwear for bouji floofs

instagramUrl: https://instagram.com/lookandpawsofficial
twitterUrl: https://twitter.com/lookandpaws
linktreeUrl: https://linktr.ee/lookandpaws

blogHomePageUrl: /blog

blogTitleOne: How To Keep Your Pet Entertained During Lockdown
blogDescriptionOne: Pets, in particular dogs, do not always deal very well with a sudden change in routine. Fortunately, we’ve put together a series of steps you can follow, to ensure that things go as smoothly as possible for you and your furry friend during lockdown!
blogPostedDateOne: March 21st, 2020
blogAuthoredByOne: Look and Paws
blogLandscapeImageOne:
blogUrlOne: /blog/how-to-keep-pet-entertained-during-lockdown


plugins:
  - jekyll-environment-variables
