baseurl: ''
permalink: pretty
title: Look and Paws
slogan: Sassy petwear for bouji floofs

instagram: instagram
instagramUrl: https://instagram.com/lookandpawsofficial

google_analytics_id: null

plugins:
  - jekyll-environment-variables
