baseurl: ''
permalink: pretty
title: Look and Paws
sloganPrefix: Sassy petwear
sloganSuffix: for bouji floofs

logoLong: /images/look-and-paws-logo.png

rootDomainWebsiteUrl: /
instagramUrl: https://instagram.com/lookandpawsofficial
twitterUrl: https://twitter.com/lookandpaws
pinterestUrl: https://www.pinterest.co.uk/lookandpaws
linktreeUrl: https://linktr.ee/lookandpaws

instagramHashtagUrl: https://www.instagram.com/explore/tags/lookandpaws/

blogHomePageUrl: https://blog.lookandpaws.com

plugins:
  - jekyll-environment-variables
