baseurl: ''
permalink: pretty
title: Look and Paws
slogan: Sassy petwear for bouji floofs

instagramUrl: https://instagram.com/lookandpawsofficial
twitterUrl: https://twitter.com/lookandpaws
linktreeUrl: https://linktr.ee/lookandpaws

blogHomePageUrl: /blog

plugins:
  - jekyll-environment-variables
