baseurl: ''
permalink: pretty
title: Look and Paws
slogan: For people with sass pets and bouji floofs

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
